### ISSUE TITLE
catch an error when running AbelSand.exe

### ISSUE THREAD

**Issue by okina850** [hayk314/Sandpiles#2]
I downloaded this folder and I'm trying to run AbelSand.exe on Windows 10 PC (64bit), but I catch some error messages saying 

"The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem."
"The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem."
"The code execution cannot proceed because ucrtbased.dll was not found. Reinstalling the program may fix this problem."

and the program doesn't start.
I searched for some trouble-shootings at these errors and tried one of them , reinstalling Microsoft Visual C++ (x86 and x64 at the same time) from the website of Microsoft, but it doesn't work.

If it is difficult to implement this app on my PC ,  I don't care abouot an environment as long as I can use some useful functions for simulating Abelian Sandpile Model.

I would appreciate if someone tells me some advices of this.

**Comment by okina850** [comment]
Excuse me, I misread the names of files the error message required. It was not "MSVCP140.dll" but  "MSVCP140D.dll", which includes "D" after "140".(and the same for "VCRUNTIME")
I think this project might not  be a release version and I don't know how to let this Debug version of AbelSand.exe implemented 
 (how to solve this error ) on my PC.
Would it be solved if you would publish a release version of this project? (I would really appreciate if you could do.)

I'm sorry if I am being impolite or too straightforward. (I'm not accustomed to engineering things.)

Sincerly,

**Comment by hayk314** [comment]
@okina850 please try to use the compiled program at C++/AbelSand/x64/Release/AbelSand.exe.
It is build for x64 platforms, so if you're on Windows x64, the program should work.  Otherwise, you may try building it from the source using a c++ compiler available for your system.

**Comment by okina850** [comment]
Thank you for your quick response. 
I tried implementing C++/AbelSand/x64/Release/AbelSand.exe, and it worked properly.

Sincerly.
